name: CodeClarity Action
description: Runs a CodeClarity scan
author: CodeClarityCE

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: crosshair
  color: black

# Define your inputs here.
inputs:
  branch:
    description: The branch you want to analyze
    required: true
    default: 'main'

  serverUrl:
    description: The url of the GitHub server
    required: true
    default: 'github.com'

  projectName:
    description: The project you want to analyze
    required: true
    default: 'CodeClarityCE/frontend'

  analyzerName:
    description: The analyzer you want to use
    required: true
    default: 'JavaScript Analyzer'

  failOnCritical:
    description: Fail the action if critical vulnerabilities are found
    required: false
    default: 'true'

  failOnHigh:
    description: Fail the action if high vulnerabilities are found
    required: false
    default: 'true'

  failOnMedium:
    description: Fail the action if medium vulnerabilities are found
    required: false
    default: 'true'

  failOnLow:
    description: Fail the action if low vulnerabilities are found
    required: false
    default: 'true'

  failOnInfo:
    description: Fail the action if info vulnerabilities are found
    required: false
    default: 'true'

# Define your outputs here.
outputs:
  vulnerabilities:
    description: The vulnerabilities found in your project

runs:
  using: node20
  main: dist/index.js
