name: CodeClarity
description: Runs a CodeClarity scan
author: CodeClarityCE

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: crosshair
  color: black

# Define your inputs here.
inputs:
  branch:
    description: The branch you want to analyze
    required: true
    default: 'main'

  projectName:
    description: The project you want to analyze
    required: true
    default: 'CodeClarityCE/frontend'

  analyzerName:
    description: The analyzer you want to use
    required: true
    default: 'JavaScript Analyzer'

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
